# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1najjQCJ7sbOYzPmvhCPx5gB3NLfALItA
"""

# =========================================
# ENERGY CONSUMPTION FORECASTING PIPELINE
# =========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.feature_selection import f_regression

# =========================================
# Load Dataset (already uploaded to Colab)
# =========================================

df = pd.read_excel("Energy Consumption Dataset For Smart Homes.xlsx")

print("Dataset Shape:", df.shape)
print(df.head())

# =========================================
# Data Preprocessing
# =========================================

df.columns = df.columns.str.strip()

df['TimeStamp'] = pd.to_datetime(df['TimeStamp'])

df['Hour'] = df['TimeStamp'].dt.hour
df['Day'] = df['TimeStamp'].dt.day
df['Month'] = df['TimeStamp'].dt.month

# Total consumption
df['Total_Consumption'] = df[['Ventilador','PC','AC','Lampara','TV']].sum(axis=1)

# =========================================
# Correlation Matrix
# =========================================

plt.figure(figsize=(10,7))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

# =========================================
# Feature Extraction
# =========================================

features = df.groupby('Hour')['Total_Consumption'].agg(
    avg_consumption='mean',
    variance='var',
    peak_consumption='max'
).reset_index()

features = features.fillna(0)

print(features.head())

# =========================================
# Clustering
# =========================================

scaler = StandardScaler()

X_cluster = scaler.fit_transform(
    features[['avg_consumption','variance','peak_consumption']]
)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)

features['Cluster'] = kmeans.fit_predict(X_cluster)

print(features)

# =========================================
# Cluster Visualization
# =========================================

plt.figure(figsize=(8,6))

sns.scatterplot(
    x=features['avg_consumption'],
    y=features['peak_consumption'],
    hue=features['Cluster'],
    palette='viridis',
    s=120
)

plt.title("Energy Consumption Clusters")
plt.xlabel("Average Consumption")
plt.ylabel("Peak Consumption")

plt.show()

# =========================================
# Prepare Data for Prediction
# =========================================

X = df[['Ventilador','PC','AC','Lampara','TV','Hour']]
y = df['Total_Consumption']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =========================================
# Random Forest Model
# =========================================

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

# =========================================
# Gradient Boosting Model
# =========================================

gb = GradientBoostingRegressor()

gb.fit(X_train, y_train)

gb_pred = gb.predict(X_test)

# =========================================
# Model Evaluation
# =========================================

def evaluate_model(y_true, y_pred):

    rmse = np.sqrt(mean_squared_error(y_true,y_pred))
    mae = mean_absolute_error(y_true,y_pred)
    r2 = r2_score(y_true,y_pred)

    print("RMSE:", rmse)
    print("MAE:", mae)
    print("R² Score:", r2)

print("\nRandom Forest Performance")
evaluate_model(y_test, rf_pred)

print("\nGradient Boosting Performance")
evaluate_model(y_test, gb_pred)

# =========================================
# F Score Feature Importance
# =========================================

f_scores, p_values = f_regression(X, y)

fscore_df = pd.DataFrame({
    "Feature": X.columns,
    "F_score": f_scores,
    "p_value": p_values
})

print("\nF Score Analysis")
print(fscore_df)

# =========================================
# Random Forest Feature Importance
# =========================================

importance = pd.Series(rf.feature_importances_, index=X.columns)

importance.sort_values().plot(kind='barh', figsize=(8,6))

plt.title("Random Forest Feature Importance")

plt.show()

# =========================================
# Prediction vs Actual
# =========================================

plt.figure(figsize=(8,6))

plt.scatter(y_test, rf_pred)

plt.xlabel("Actual Consumption")
plt.ylabel("Predicted Consumption")

plt.title("Random Forest: Actual vs Predicted")

plt.show()

# =========================================
# Cluster Consumption Analysis
# =========================================

cluster_analysis = features.groupby('Cluster').mean()

print("\nCluster Consumption Patterns")
print(cluster_analysis)